projects:
  dev:
    schemaPath: src/graphql/schema.json
    includes:
      - scr/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: scr/graphql
extensions:
  amplify:
    version: 3
